project:
  type: website
  output-dir: docs    # Option A: publish /docs on main
  resources:
    - files/**
    - assets/**
    - robots.txt
    
website:
  title: "Evidence-Based Engineering"
  site-url: "https://vincepileggi.github.io/engineering-stats/"

  page-footer:
    center: |
       © 2026 Vince Pileggi · Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/){target="_blank"}  
       Views are my own and do not represent my employer or affiliated organizations.
  
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Resources"
        href: resources.qmd
      - href: license.qmd
        text: License

    right:
      - icon: github
        href: "https://github.com/VincePileggi/engineering-stats"

  search: true
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
    page-footer:
      left: "© 2024 Vince Pileggi"
      center: "Evidence-Based Engineering"
      right: "Built with Quarto"  
    number-sections: false
    include-before-body: notice.html
    include-after-body:
      text: |
        <script src="open-external-links.js"></script>
